# ***************************************
# * Parameters for metagenotate pipeline *
# ***************************************

#list_files: "/bulk/sycuro_bulk/lsycuro_labshare/kevin/wgs_annotated_assembly/utils/ref_list.txt"

list_files: "/bulk/sycuro_bulk/lsycuro_labshare/kevin/wgs_annotated_assembly/utils/twist96_3_ref_list.txt"

# Path to fastq_files.
#input_dir: "/home/kevin.muirhead/fastq"

input_dir: "/bulk/IMCshared_bulk/sycuro_shared_projects/Twist96/novaseq_run/data/Plate1_L001"

output_dir: "/bulk/sycuro_bulk/lsycuro_labshare/kevin/wgs_annotated_assembly_test"

# Suffix for forward reads.
#forward_read_suffix: "_R1.fastq.gz"
forward_read_suffix: "_R1.fastq.gz"

# Suffix for reverse reads.
#reverse_read_suffix: "_R2.fastq.gz"
reverse_read_suffix: "_R2.fastq.gz"

### Prinseq parameters
trimleft: 0
trimright: 0
trim_qual_left: 30
trim_qual_right: 30
trim_qual_window: 10
trim_qual_step : 2
trim_qual_type: "mean"
trim_qual_rule: "lt"
lc_method: "dust"
lc_threshold: 7

# Minimum length for reads
minlength: 60

# Maximum number of N bases allowed
maxn: 15

### Spades parameters

# Number of threads for spades.
assembler_threads: 28

# Memory in GB for spades.
memory_in_gb: 220

## Filter by length

# Minimum sequence length of the final genome assembly file. Default: 500
min_scaffold_length: 500

### quast parameters.

# Number of threads for quast rule.
quast_threads: 14

###  prokka parameters.

# Number of threads for prokka rule.
prokka_threads: 14

### metaerg parameters.

# metaerg database path.
metaerg_database_path: "/bulk/IMCshared_bulk/shared/dbs/metaerg_db/db"

# singularity working directories.
working_dirs: ["/work","/bulk"]

metaerg_threads: 14

### CheckM parameters.

checkm_database_path: "/bulk/IMCshared_bulk/shared/dbs/checkm_db"

# Number of threads for checkm rule.
checkm_threads: 28

### GTDB-tk parameters.

gtdbtk_database_path: "/bulk/IMCshared_bulk/shared/dbs/gtdbtk-1.5.0/db"

# Number of threads for gtdbtk rule.
gtdbtk_threads: 28

### eggnog-mapper parameters
eggnog_mapper_db: "/bulk/IMCshared_bulk/shared/shared_software/eggnog-mapper/data"

eggnog_mapper_threads: 14

#
